"""add hashed_password to users

Revision ID: 32a97f2d4c52
Revises: c63a19a60f63
Create Date: 2026-06-18 18:44:12.803721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32a97f2d4c52'
down_revision: Union[str, Sequence[str], None] = 'c63a19a60f63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=True))
    op.execute("UPDATE users SET hashed_password = 'temporal_hash' WHERE hashed_password IS NULL")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
